// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1Kv-w1zb2mfT_yVzaPLyegnc3sHL9e10',
    appId: '1:594811220594:web:c236dffb11159e041348eb',
    messagingSenderId: '594811220594',
    projectId: 'deploy-e2292',
    authDomain: 'deploy-e2292.firebaseapp.com',
    storageBucket: 'deploy-e2292.firebasestorage.app',
    measurementId: 'G-VD4P62NHZ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSDCQVEVXv4g_rM8uDqo81sjutlSv8lp4',
    appId: '1:594811220594:android:760c984e5bea743b1348eb',
    messagingSenderId: '594811220594',
    projectId: 'deploy-e2292',
    storageBucket: 'deploy-e2292.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAZG-fXxJLf9kC9TQUf6cS9swClRkmsKo',
    appId: '1:594811220594:ios:5ae84d5e6cbc458a1348eb',
    messagingSenderId: '594811220594',
    projectId: 'deploy-e2292',
    storageBucket: 'deploy-e2292.firebasestorage.app',
    iosBundleId: 'com.example.ecommercepro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAZG-fXxJLf9kC9TQUf6cS9swClRkmsKo',
    appId: '1:594811220594:ios:5ae84d5e6cbc458a1348eb',
    messagingSenderId: '594811220594',
    projectId: 'deploy-e2292',
    storageBucket: 'deploy-e2292.firebasestorage.app',
    iosBundleId: 'com.example.ecommercepro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1Kv-w1zb2mfT_yVzaPLyegnc3sHL9e10',
    appId: '1:594811220594:web:9b01fe9c978c1c731348eb',
    messagingSenderId: '594811220594',
    projectId: 'deploy-e2292',
    authDomain: 'deploy-e2292.firebaseapp.com',
    storageBucket: 'deploy-e2292.firebasestorage.app',
    measurementId: 'G-B6GSNBGMJE',
  );

}